### Get the root URL
GET http://localhost:8000


### Get all the tasks
GET http://localhost:8000/api/v1/task


### Post tasks to fakeTasks array
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task": "Exploring",
    "hour": 33
}

### Update the type of the task
PATCH http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id":"6487153a89dcbcbcbe9645d8",
    "type":"bad"
}

### Delete the task from the array
DELETE http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id":"6487153a89dcbcbcbe9645d8"
}




